### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by peppecacace** [Ciromaiello/VideogameTime#1]
@pcantiello salve prof, come da lei suggerito abbiamo cambiato il modo di fare la nostra query, però abbiamo provato un'altra soluzione che non richiedesse l'utilizzo di raccolte "generi " e "piattaforme " perché come fatto rispetto all'ultimo commit(il codice aggiunto per le query si trova in GeneriAdapter e PiattaformeAdapter nell'OnCheckedChanged) funziona anche andando sulla raccolta "giochi" direttamente, ora però ci chiedevamo se effettivamente avessimo risolto il problema dei listener aperti in parallelo con questa soluzione, attendiamo una risposta ed eventualmente dei suggerimenti in merito

**Comment by pcantiello** [comment]
Cari ragazzi,
da quello che vedo, ogni volta che fate click su un checkbox, parte una nuova query di tutti i giochi di quel genere? Quindi se io seleziono uno dopo l'altro più generi, partono più query, ognuna delle quali estrae più giochi che si possono pure sovrapporre generando duplicati in nomige. E poi in questo modo sono anche costretto, dopo aver letto tutti i generi ad effettuare un nuovo controllo con iscecked().
Non mi piace molto ...
