### ISSUE TITLE
abbiamo finito 

### ISSUE THREAD

**Issue by peppecacace** [Ciromaiello/VideogameTime#2]
@pcantiello Salve prof, noi abbiamo finito di sviluppare l'app secondo le nostre idee, contando dei giorni per risolvere eventuali ultimi bug durante le prove e per fare una presentazione noi saremmo pronti a presentare l'app dal 9 gennaio, ci può far sapere lei quando è possibile venire? Magari nel frattempo può dare uno sguardo al codice se ci sono errori gravi come quelli dei listener in paralello nelle scorse settimane..

**Comment by pcantiello** [comment]
Cari ragazzi, per me possiamo vederci quando volete. Questa settimana sarò sempre qui. 
Per l'esame ho fissato una seduta d'esame proprio per oggi pomeriggio, però se voi dite dal 9 in poi, ne dobbiamo fissare un'altra. Cerco di dare un'occhiata al codice.
